### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Unreeling8562** [FormBee/FormBee#1]
Hi the project good :) Any plans for adding a docker image?

**Comment by Oia20** [comment]
Yes! planning to make a public docker image. ATM there's a dockerfile in the server directory as well.

**Comment by Oia20** [comment]
Added a section to the docs that link to the official self hosting docs, and now have a directory titled "docker-images" where I'll be adding more and more images for just self hosting what you need, and not what you dont.
